export const GET_COMPONENTS = "GET_COMPONENTS";
export const GET_PAGINATION_COMPONENTS = "GET_PAGINATION_COMPONENTS";
export const GET_FEATURED_COMPONENTS = "GET_FEAUTRED_COMPONENTS";
export const GET_CURRENT_COMPONENT = "GET_CURRENT_COMPONENT";
export const GET_USERS = "GET_USERS";
export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const GET_COMPONENT_STATISTICS = "GET_COMPONENT_STATISTICS";
export const GET_USER_STATISTICS = "GET_USER_STATISTICS";
